const initialMovies = [
    { title: "Blade", poster: "assets/Blade.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Wesley Snipes", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Cody Banks", poster: "assets/Cody banks.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Frankie Muniz", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Dans la peau de ma mère", poster: "assets/Dans la peau de ma mère.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jamie Lee Curtis, Lindsay Lohan", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Desperados", poster: "assets/Desperados .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Antonio Banderas", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Dinotopia", poster: "assets/Dinotopia .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Fast and Furious Tokyo Drift", poster: "assets/Fast and furious Tokyo drift .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Lucas Black", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Georges de la jungle", poster: "assets/Georges de la jungle.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Brendan Fraser", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Gladiator", poster: "assets/Gladiator .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Russell Crowe", quotes: [], comments: "", platforms: "Netflix, Prime" },
    { title: "Kung Fu Nanny", poster: "assets/Kung fu nanny.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jackie Chan", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Drôle de Noël de Scrooge", poster: "assets/Le drole de noël de scrooge .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jim Carrey", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Magic Basket", poster: "assets/Magic basket.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Bow Wow", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Mathilda", poster: "assets/Mathilda.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Mara Wilson", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Million Dollar Baby", poster: "assets/Millions dollar baby .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Hilary Swank", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Ong Bak", poster: "assets/Ong bak.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Tony Jaa", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Princesse Mononoké", poster: "assets/Princesse Mononoké.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Racine", poster: "assets/Racine.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Retour vers le futur 1", poster: "assets/Retour vers le futur 1 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Michael J. Fox", quotes: [], comments: "", platforms: "Netflix, Prime" },
    { title: "Roméo doit mourir", poster: "assets/Roméo doit mourir .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jet Li", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Scooby-Doo", poster: "assets/Scooby doo .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Matthew Lillard", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Scooby-Doo 2", poster: "assets/Scooby doo 2.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Matthew Lillard", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Shaolin Soccer", poster: "assets/Shaolin soccer .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Stephen Chow", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Step Up", poster: "assets/Stepin .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Channing Tatum", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Secret de Terabithia", poster: "assets/Terabithia.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Josh Hutcherson", quotes: [], comments: "", platforms: "Disney+" },
    { title: "The Mask", poster: "assets/The mask.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jim Carrey", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Willow", poster: "assets/Willow.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Warwick Davis", quotes: [], comments: "", platforms: "Disney+" },
    { title: "À nous 4", poster: "assets/A nous 4  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Lindsay Lohan", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Arthur et les Minimoys", poster: "assets/Arthur et les minimoys  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Freddie Highmore", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Au revoir à jamais", poster: "assets/Au revoir à jamais_.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Geena Davis", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Azur et Asmar", poster: "assets/Azur et Asmar.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Banlieue 13", poster: "assets/B13 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Cyril Raffaelli", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Baby-Sittor", poster: "assets/Babysittor .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Vin Diesel", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Bad Boys II", poster: "assets/Bad Boys II.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Will Smith, Martin Lawrence", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Batman Begins", poster: "assets/Batman Begins.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Christian Bale", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Benjamin Gates", poster: "assets/Benjamin Gates et le secret des templiers .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Nicolas Cage", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Bibi Blocksberg", poster: "assets/Bibi blocksberg.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Big Mamma", poster: "assets/Big mama.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Martin Lawrence", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Brice de Nice", poster: "assets/Brice de Nice .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jean Dujardin", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Charlie's Angels", poster: "assets/Charly Angel  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Cameron Diaz", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Chevalier", poster: "assets/Chevalier .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Heath Ledger", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Cinq enfants et moi", poster: "assets/Cinq enfants et moi.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Freddie Highmore", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Clone", poster: "assets/Clone.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Crocodile Dundee 2", poster: "assets/Crocodile Dundee 2 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Paul Hogan", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Crocodile Dundee", poster: "assets/Crocodile dundee    .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Paul Hogan", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Cutaway", poster: "assets/Cutaway.jpg.png", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Stephen Baldwin", quotes: [], comments: "", platforms: "Streaming" },
    { title: "DOA: Dead or Alive", poster: "assets/DOA.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jaime Pressly", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Danny the Dog", poster: "assets/Dany the dog  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jet Li", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Daredevil", poster: "assets/Daredevil .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ben Affleck", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Elysium", poster: "assets/Elysium.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Matt Damon", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Enfants non accompagnés", poster: "assets/Enfants non accompagné.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Eragon", poster: "assets/Eragon  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ed Speleers", quotes: [], comments: "", platforms: "Disney+" },
    { title: "2 Fast 2 Furious", poster: "assets/Fast and furious 2 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Paul Walker", quotes: [], comments: "", platforms: "Netflix" },
    { title: "FBI : Fausses Blondes", poster: "assets/Fbi fausses  blondes.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Marlon Wayans", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Gnoméo et Juliette", poster: "assets/Gnomes et Juliette  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Disney+" },
    { title: "The Green Hornet", poster: "assets/Green Hornet .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Seth Rogen", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Gremlins", poster: "assets/Gremlins .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Zach Galligan", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Hancock", poster: "assets/Hancock.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Will Smith", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Hellboy", poster: "assets/Hellboy.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ron Perlman", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Horton", poster: "assets/Horton.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jim Carrey", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Hulk", poster: "assets/Hulk .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Eric Bana", quotes: [], comments: "", platforms: "Streaming" },
    { title: "I, Robot", poster: "assets/I Robot.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Will Smith", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Il était une fois", poster: "assets/Il était une fois  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Amy Adams", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Incassable", poster: "assets/Incassable.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Bruce Willis", quotes: [], comments: "", platforms: "Disney+" },
    { title: "L'Incroyable Hulk", poster: "assets/Incroyable Hulk.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Edward Norton", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Jackie Chan dans le Bronx", poster: "assets/Jackie Chan dans le Bronx.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jackie Chan", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Jumanji", poster: "assets/Jumanji .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Robin Williams", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Jumper", poster: "assets/Jumper.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Hayden Christensen", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Kill Bill", poster: "assets/Kill Bill.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Uma Thurman", quotes: [], comments: "", platforms: "Streaming" },
    { title: "King Kong", poster: "assets/King Kong.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Naomi Watts", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Kung Fu Kid", poster: "assets/Kung Fu Kid .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jaden Smith", quotes: [], comments: "", platforms: "Netflix" },
    { title: "La Nuit au Musée", poster: "assets/La Nuit au Musée.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ben Stiller", quotes: [], comments: "", platforms: "Disney+" },
    { title: "La Guerre des Mondes", poster: "assets/La guerre des mondes.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Tom Cruise", quotes: [], comments: "", platforms: "Netflix" },
    { title: "La Ligue des Gentlemen Extraordinaires", poster: "assets/La ligue des gentleman extraordinaire .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Sean Connery", quotes: [], comments: "", platforms: "Disney+" },
    { title: "La Loi du Plus Fort", poster: "assets/La loi du plus fort .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "La Malédiction du Dragon", poster: "assets/La malédiction du dragon.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "La Momie", poster: "assets/La momie .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Brendan Fraser", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Le Dragon des Mers", poster: "assets/Le Dragon des Mers.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Fils du Mask", poster: "assets/Le Fils du Mask.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jamie Kennedy", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Grand Tournoi", poster: "assets/Le Grand Tournoi.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jean-Claude Van Damme", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Baiser Mortel du Dragon", poster: "assets/Le baiser mortel du Dragon.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jet Li", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Chevalier Black", poster: "assets/Le chevalier Black.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Martin Lawrence", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Choc des Titans", poster: "assets/Le choc des titans.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Sam Worthington", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Le Grand Bleu", poster: "assets/Le grand bleu .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jean Reno", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Le Roi Scorpion", poster: "assets/Le roi scorpion .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Dwayne Johnson", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Les 36 Chambres de Shaolin", poster: "assets/Les 36 chambres de Shaolin .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Gordon Liu", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Les Autres", poster: "assets/Les Autres.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Nicole Kidman", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Adèle Blanc-Sec", poster: "assets/Les aventures extraordinaires d’Adèle Blanc, sec.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Louise Bourgoin", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Les Dalton", poster: "assets/Les dalton .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Eric et Ramzy", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Les Évadés", poster: "assets/Les évadés.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Morgan Freeman", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Les Visiteurs", poster: "assets/Les visiteurs   .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jean Reno, Christian Clavier", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Les Zintrus", poster: "assets/Les zintru .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ashley Tisdale", quotes: [], comments: "", platforms: "Streaming" },
    { title: "L'Île aux Pirates", poster: "assets/L’ILE AUX PIRATES .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Geena Davis", quotes: [], comments: "", platforms: "Streaming" },
    { title: "L'Île de Nim", poster: "assets/L’île de nime jpg.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Abigail Breslin", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Magic Warriors", poster: "assets/Magic warriors .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Maman, je m'occupe des méchants", poster: "assets/Maman , je m'occupe des méchants .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Alex D. Linz", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Maman, j'ai encore raté l'avion", poster: "assets/Maman j'ai encore raté l'avion.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Macaulay Culkin", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Man of Steel", poster: "assets/Man of Steel .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Henry Cavill", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Matrix", poster: "assets/Matrix.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Keanu Reeves", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Men in Black", poster: "assets/Men in black.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Will Smith", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Méchant Menteur", poster: "assets/Méchant menteur.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Frankie Muniz", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Mon Beau-père et moi", poster: "assets/Mon beau-père et moi .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ben Stiller", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Le Monde de Narnia", poster: "assets/Narnia.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Nausicaä", poster: "assets/Nausicaâ de la vallée du vent.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Nos Voisins les Hommes", poster: "assets/Nos voisins, les hommes.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Numéro 4", poster: "assets/Numéro 4 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Alex Pettyfer", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Prince of Persia", poster: "assets/Prince of Persia.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jake Gyllenhaal", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Ratatouille", poster: "assets/Ratatouille .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Retour vers le futur 2", poster: "assets/Retour vers le futur 2 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Michael J. Fox", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Riddick", poster: "assets/Riddik.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Vin Diesel", quotes: [], comments: "", platforms: "Streaming" },
    { title: "R.I.P.D.", poster: "assets/Ripd fantôme.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Ryan Reynolds", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Robin des Bois", poster: "assets/Robin des bois.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Kevin Costner", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Samy la Tortue", poster: "assets/Samy la tortue.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Sexy Dance 3", poster: "assets/Sexy dance 3.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Shark Attack 3", poster: "assets/Shark attack 3.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Osmosis Jones", poster: "assets/Simon au pays des globuldes.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Bill Murray", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Small Soldiers", poster: "assets/Small Soldiers .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Kirsten Dunst", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Space Jam", poster: "assets/Space Jam.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Michael Jordan", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Spider-Man 3", poster: "assets/Spider-Man 3.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Tobey Maguire", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Les Chroniques de Spiderwick", poster: "assets/Spiderweak.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Freddie Highmore", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Spy Kids", poster: "assets/Spy, kids .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Alexa Vega", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Taxi 4", poster: "assets/TAXI 4 .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Samy Naceri", quotes: [], comments: "", platforms: "Netflix" },
    { title: "The Dark Knight", poster: "assets/The Dark Knight .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Christian Bale", quotes: [], comments: "", platforms: "Netflix" },
    { title: "The Dark Knight Rises", poster: "assets/The Dark Knight Rises .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Christian Bale", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Titanic", poster: "assets/Titanic  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Leonardo DiCaprio", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Total Recall", poster: "assets/Total Recall .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Arnold Schwarzenegger", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Transformers", poster: "assets/Transformers.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Shia LaBeouf", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Le Transporteur", poster: "assets/Transporteur.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jason Statham", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Troie", poster: "assets/Troie.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Brad Pitt", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Vic le Viking", poster: "assets/Vic le viking .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Volte-Face", poster: "assets/Volteface.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "John Travolta, Nicolas Cage", quotes: [], comments: "", platforms: "Disney+" },
    { title: "Wallace et Gromit", poster: "assets/Wallace et Gromit .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Watchmen", poster: "assets/Watchmen  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jackie Earle Haley", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Wild Wild West", poster: "assets/Wild Wild West .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Will Smith", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Zathura", poster: "assets/Zathura .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Josh Hutcherson", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Commando", poster: "assets/comando.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Arnold Schwarzenegger", quotes: [], comments: "", platforms: "Disney+" },
    { title: "La Ligne Verte", poster: "assets/la ligne vert  .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Tom Hanks", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Le Château Ambulant", poster: "assets/le chateau ambulant .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "", quotes: [], comments: "", platforms: "Netflix" },
    { title: "Les Fils du Vent", poster: "assets/les fils du vent.png.jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Yamakasi", quotes: [], comments: "", platforms: "Streaming" },
    { title: "Nicky Larson", poster: "assets/nicky larson .jpg", trailer: "", rating: { O: 0, M: 0, L: 0 }, actors: "Jackie Chan", quotes: [], comments: "", platforms: "Streaming" }
];
